# Generated by Django 3.1.4 on 2023-02-18 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210112_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 18, 40, 14, 169178, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 18, 40, 14, 169178, tzinfo=utc)),
        ),
    ]
